let handler = m => m

handler.before = function (m) {
  let user = global.db.data.users[m.sender]
  let level = user.level
  let role

  if (level <= 1) {
    role = 'Novato'
  } else if (level <= 10) {
    role = 'Aprendiz'
  } else if (level <= 20) {
    role = 'Principiante'
  } else if (level <= 30) {
    role = 'Entrenado'
  } else if (level <= 40) {
    role = 'Iniciado'
  } else if (level <= 50) {
    role = 'Aspirante'
  } else if (level <= 60) {
    role = 'Estudiante'
  } else if (level <= 70) {
    role = 'Aprendiz avanzado'
  } else if (level <= 80) {
    role = 'Intermedio'
  } else if (level <= 90) {
    role = 'Avanzado'
  } else if (level <= 100) {
    role = 'Experto'
  } else if (level <= 110) {
    role = 'Maestro'
  } else if (level <= 120) {
    role = 'Especialista'
  } else if (level <= 130) {
    role = 'Instructor'
  } else if (level <= 140) {
    role = 'Guía'
  } else if (level <= 150) {
    role = 'Líder'
  } else if (level <= 160) {
    role = 'Mentor'
  } else if (level <= 170) {
    role = 'Consultor'
  } else if (level <= 180) {
    role = 'Experto senior'
  } else if (level <= 190) {
    role = 'Autoridad'
  } else if (level <= 200) {
    role = 'Elite'
  } else if (level <= 210) {
    role = 'Campeón'
  } else if (level <= 220) {
    role = 'Legendario'
  } else if (level <= 230) {
    role = 'Heroico'
  } else if (level <= 240) {
    role = 'Épico'
  } else if (level <= 250) {
    role = 'Famoso'
  } else if (level <= 260) {
    role = 'Ilustre'
  } else if (level <= 270) {
    role = 'Destacado'
  } else if (level <= 280) {
    role = 'Eminente'
  } else if (level <= 290) {
    role = 'Excelente'
  } else if (level <= 300) {
    role = 'Maestro supremo'
  } else if (level <= 310) {
    role = 'Gran maestro'
  } else if (level <= 320) {
    role = 'Experto supremo'
  } else if (level <= 330) {
    role = 'Autoridad suprema'
  } else if (level <= 340) {
    role = 'Líder supremo'
  } else if (level <= 350) {
    role = 'Mentor supremo'
  } else if (level <= 360) {
    role = 'Guía supremo'
  } else if (level <= 370) {
    role = 'Instructor supremo'
  } else if (level <= 380) {
    role = 'Especialista supremo'
  } else if (level <= 390) {
    role = 'Leyenda'
  } else if (level <= 400) {
    role = 'Icono'
  } else if (level <= 410) {
    role = 'Monumento'
  } else if (level <= 420) {
    role = 'Símbolo'
  } else if (level <= 430) {
    role = 'Referente'
  } else if (level <= 440) {
    role = 'Modelo'
  } else if (level <= 450) {
    role = 'Inspiración'
  } else if (level <= 460) {
    role = 'Ídolo'
  } else if (level <= 470) {
    role = 'Héroe'
  } else if (level <= 480) {
    role = 'Mitología'
  } else if (level <= 490) {
    role = 'Dios'
  } else if (level <= 500) {
    role = 'Dios supremo'
}

user.role= role
return true
}

export default handler